spring:
  application:
    name: blog-backend
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blogdb?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: bloguser
    password: bloguser
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.example.blog: debug

# 文件上传配置
file:
  upload-dir: /home/ec2-user/uploads
  max-image-size: 5242880  # 5MB
  max-video-size: 52428800 # 50MB
  allowed-image-types: jpg,jpeg,png,gif,webp
  allowed-video-types: mp4,webm,mov
